version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - ./wp-content/:/var/www/html/wp-content/
      - ./wp-config.php:/var/www/html/wp-config.php

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - .data/db:/var/lib/mysql